# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer1.workspace:
                                             
  peer1.apple.workspace:
  peer2.apple.workspace:
  peer1.microsoft.workspace:
  peer2.microsoft.workspace:
  peer1.fiserv.workspace:
  peer2.fiserv.workspace:
  peer1.cbAccounts.workspace:
  peer2.cbAccounts.workspace:
  peer1.citizenBank.workspace:
  peer2.citizenBank.workspace:


networks:
  byfn:

services:
  orderer1.workspace:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer1.workspace
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/workspace/orderers/orderer1.workspace/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/workspace/orderers/orderer1.workspace/tls/:/var/hyperledger/orderer/tls
        - orderer1.workspace:/var/hyperledger/production/orderer
    ports:
    - 7050:7050

 
  peer1.apple.workspace:
    container_name: peer1.apple.workspace
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.apple.workspace
      - CORE_PEER_ADDRESS=peer1.apple.workspace:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.apple.workspace:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.apple.workspace:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.apple.workspace:7051
      - CORE_PEER_LOCALMSPID=appleMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/apple.workspace/peers/peer1.apple.workspace/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/apple.workspace/peers/peer1.apple.workspace/tls:/etc/hyperledger/fabric/tls
        - peer1.apple.workspace:/var/hyperledger/production
    ports:
      - 7051:7051
    networks:
      - byfn

  peer2.apple.workspace:
    container_name: peer2.apple.workspace
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.apple.workspace
      - CORE_PEER_ADDRESS=peer2.apple.workspace:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer2.apple.workspace:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1. .workspace:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.apple.workspace:8051
      - CORE_PEER_LOCALMSPID=appleMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/apple.workspace/peers/peer2.apple.workspace/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/apple.workspace/peers/peer2.apple.workspace/tls:/etc/hyperledger/fabric/tls
        - peer2.apple.workspace:/var/hyperledger/production
    ports:
      - 8051:8051
    networks:
      - byfn

  peer1.microsoft.workspace:
    container_name: peer1.microsoft.workspace
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.microsoft.workspace
      - CORE_PEER_ADDRESS=peer1.microsoft.workspace:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer1.microsoft.workspace:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.microsoft.workspace:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.microsoft.workspace:9051
      - CORE_PEER_LOCALMSPID=microsoftMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/microsoft.workspace/peers/peer1.microsoft.workspace/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/microsoft.workspace/peers/peer1.microsoft.workspace/tls:/etc/hyperledger/fabric/tls
        - peer1.microsoft.workspace:/var/hyperledger/production
    ports:
      - 9051:9051
    networks:
      - byfn

  peer2.microsoft.workspace:
    container_name: peer2.microsoft.workspace
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.microsoft.workspace
      - CORE_PEER_ADDRESS=peer2.microsoft.workspace:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer2.microsoft.workspace:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.microsoft.workspace:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.microsoft.workspace:10051
      - CORE_PEER_LOCALMSPID=microsoftMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/microsoft.workspace/peers/peer2.microsoft.workspace/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/microsoft.workspace/peers/peer2.microsoft.workspace/tls:/etc/hyperledger/fabric/tls
        - peer2.microsoft.workspace:/var/hyperledger/production
    ports:
      - 10051:10051
    networks:
      - byfn

  peer1.fiserv.workspace:
    container_name: peer1.fiserv.workspace
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.fiserv.workspace
      - CORE_PEER_ADDRESS=peer1.fiserv.workspace:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer1.fiserv.workspace:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.fiserv.workspace:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.fiserv.workspace:11051
      - CORE_PEER_LOCALMSPID=fiservMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/fiserv.workspace/peers/peer1.fiserv.workspace/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/fiserv.workspace/peers/peer1.fiserv.workspace/tls:/etc/hyperledger/fabric/tls
        - peer1.fiserv.workspace:/var/hyperledger/production
    ports:
      - 11051:11051
    networks:
      - byfn

  peer2.fiserv.workspace:
    container_name: peer2.fiserv.workspace
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.fiserv.workspace
      - CORE_PEER_ADDRESS=peer2.fiserv.workspace:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer2.fiserv.workspace:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.fiserv.workspace:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.fiserv.workspace:12051
      - CORE_PEER_LOCALMSPID=fiservMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/fiserv.workspace/peers/peer2.fiserv.workspace/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/fiserv.workspace/peers/peer2.fiserv.workspace/tls:/etc/hyperledger/fabric/tls
        - peer2.fiserv.workspace:/var/hyperledger/production
    ports:
      - 12051:12051
    networks:
      - byfn

  peer1.cbAccounts.workspace:
    container_name: peer1.cbAccounts.workspace
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.cbAccounts.workspace
      - CORE_PEER_ADDRESS=peer1.cbAccounts.workspace:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer1.cbAccounts.workspace:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.cbAccounts.workspace:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.cbAccounts.workspace:13051
      - CORE_PEER_LOCALMSPID=cbAccountsMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/cbAccounts.workspace/peers/peer1.cbAccounts.workspace/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/cbAccounts.workspace/peers/peer1.cbAccounts.workspace/tls:/etc/hyperledger/fabric/tls
        - peer1.cbAccounts.workspace:/var/hyperledger/production
    ports:
      - 13051:13051
    networks:
      - byfn

  peer2.cbAccounts.workspace:
    container_name: peer2.cbAccounts.workspace
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.cbAccounts.workspace
      - CORE_PEER_ADDRESS=peer2.cbAccounts.workspace:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer2.cbAccounts.workspace:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.cbAccounts.workspace:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.cbAccounts.workspace:14051
      - CORE_PEER_LOCALMSPID=cbAccountsMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/cbAccounts.workspace/peers/peer2.cbAccounts.workspace/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/cbAccounts.workspace/peers/peer2.cbAccounts.workspace/tls:/etc/hyperledger/fabric/tls
        - peer2.cbAccounts.workspace:/var/hyperledger/production
    ports:
      - 14051:14051
    networks:
      - byfn

  peer1.citizenBank.workspace:
    container_name: peer1.citizenBank.workspace
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.citizenBank.workspace
      - CORE_PEER_ADDRESS=peer1.citizenBank.workspace:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer1.citizenBank.workspace:15052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.citizenBank.workspace:16051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.citizenBank.workspace:15051
      - CORE_PEER_LOCALMSPID=citizenBankMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/citizenBank.workspace/peers/peer1.citizenBank.workspace/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/citizenBank.workspace/peers/peer1.citizenBank.workspace/tls:/etc/hyperledger/fabric/tls
        - peer1.citizenBank.workspace:/var/hyperledger/production
    ports:
      - 15051:15051
    networks:
      - byfn

  peer2.citizenBank.workspace:
    container_name: peer2.citizenBank.workspace
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.citizenBank.workspace
      - CORE_PEER_ADDRESS=peer2.citizenBank.workspace:16051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:16051
      - CORE_PEER_CHAINCODEADDRESS=peer2.citizenBank.workspace:16052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:16052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.citizenBank.workspace:15051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.citizenBank.workspace:16051
      - CORE_PEER_LOCALMSPID=citizenBankMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/citizenBank.workspace/peers/peer2.citizenBank.workspace/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/citizenBank.workspace/peers/peer2.citizenBank.workspace/tls:/etc/hyperledger/fabric/tls
        - peer2.citizenBank.workspace:/var/hyperledger/production
    ports:
      - 16051:16051
    networks:
      - byfn



  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    dns_search: .
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.apple.workspace:7051
      - CORE_PEER_LOCALMSPID=appleMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/apple.workspace/peers/peer1.apple.workspace/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/apple.workspace/peers/peer1.apple.workspace/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/apple.workspace/peers/peer1.apple.workspace/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/apple.workspace/users/Admin@apple.workspace/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./myscripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/myscripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer1.workspace
      
      - peer1.apple.workspace
      - peer2.apple.workspace
      - peer1.microsoft.workspace
      - peer2.microsoft.workspace
      - peer1.fiserv.workspace
      - peer2.fiserv.workspace
      - peer1.cbAccounts.workspace
      - peer2.cbAccounts.workspace
      - peer1.citizenBank.workspace
      - peer2.citizenBank.workspace
     
     
    networks:
      - byfn


  # ca1:
  #   extends:
  #     file: base.yaml
  #     service: ca-base
  #   environment:
  #     - FABRIC_CA_SERVER_CA_NAME=ca-apple
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.apple.workspace-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a75d012725ef434f86c9d31f02e748922f9d81f0dfcbb9e4890f1dfbd69a0424_sk
  #     - FABRIC_CA_SERVER_PORT=7054
  #   ports:
  #     - "7054:7054"
  #   command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.apple.workspace-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a75d012725ef434f86c9d31f02e748922f9d81f0dfcbb9e4890f1dfbd69a0424_sk -b admin:adminpw -d'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/apple.workspace/ca/:/etc/hyperledger/fabric-ca-server-config
  #   container_name: ca_apple
    

  # ca2:
  #   extends:
  #     file: base.yaml
  #     service: ca-base
  #   environment:
  #     - FABRIC_CA_SERVER_CA_NAME=ca-microsoft
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.microsoft.workspace-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/caf48a1b5c6e3d0afa0ef05ff9e42dd890f7a64299d7a7a1cd0da301ffc65263_sk
  #     - FABRIC_CA_SERVER_PORT=9054
  #   ports:
  #     - "9054:9054"
  #   command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.microsoft.workspace-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/caf48a1b5c6e3d0afa0ef05ff9e42dd890f7a64299d7a7a1cd0da301ffc65263_sk -b admin:adminpw -d'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/microsoft.workspace/ca/:/etc/hyperledger/fabric-ca-server-config
  #   container_name: ca_finance

  # ca3:
  #   extends:
  #     file: base.yaml
  #     service: ca-base
  #   environment:
  #     - FABRIC_CA_SERVER_CA_NAME=ca-fiserv
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.fiserv.workspace-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/973b6fbc8397b467ec76dc32ad61104ac77034a1e2de1b98dedbb787c0540def_sk
  #     - FABRIC_CA_SERVER_PORT=11054
  #   ports:
  #     - "11054:11054"
  #   command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.fiserv.workspace-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/973b6fbc8397b467ec76dc32ad61104ac77034a1e2de1b98dedbb787c0540def_sk -b admin:adminpw -d'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/fiserv.workspace/ca/:/etc/hyperledger/fabric-ca-server-config
  #   container_name: ca_hr
  
  # ca4:
  #   extends:
  #     file: base.yaml
  #     service: ca-base
  #   environment:
  #     - FABRIC_CA_SERVER_CA_NAME=ca-cbAccounts
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cbAccounts.workspace-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/82b1b4f6bf80f8b948f8aac606ae7a46f8605b221e309b8cc3edea307020e56d_sk
  #     - FABRIC_CA_SERVER_PORT=13054
  #   ports:
  #     - "13054:13054"
  #   command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.cbAccounts.workspace-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/82b1b4f6bf80f8b948f8aac606ae7a46f8605b221e309b8cc3edea307020e56d_sk -b admin:adminpw -d'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/cbAccounts.workspace/ca/:/etc/hyperledger/fabric-ca-server-config
  #   container_name: ca_marketing
  #   networks:
  #     - byfn  

  # ca5:
  #   extends:
  #     file: base.yaml
  #     service: ca-base
  #   environment:
  #     - FABRIC_CA_SERVER_CA_NAME=ca-citizenBank
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.citizenBank.workspace-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/82b1b4f6bf80f8b948f8aac606ae7a46f8605b221e309b8cc3edea307020e56d_sk
  #     - FABRIC_CA_SERVER_PORT=13054
  #   ports:
  #     - "15054:15054"
  #   command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.citizenBank.workspace-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/82b1b4f6bf80f8b948f8aac606ae7a46f8605b221e309b8cc3edea307020e56d_sk -b admin:adminpw -d'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/citizenBank.workspace/ca/:/etc/hyperledger/fabric-ca-server-config
  #   container_name: ca_marketing
  #   networks:
  #     - byfn  
